### ISSUE TITLE
Magento 2.3.3 throws error

### ISSUE THREAD

**Issue by SurguciClaudiu** [owebia/magento2-module-advanced-setting-core#10]
Module is not working on Magento 2.3.3
Shipping methods not showing up on cart and on checkout. (No shipping method is showing up, not even the default Magento methods)
Checkout page throws error - **"Something went wrong with your request. Please try again later."**
Console:
![owebia-error](https://user-images.githubusercontent.com/43299361/66911684-b602db80-f019-11e9-93c4-691c34bb1509.jpg)

Regards

**Comment by owebia** [comment]
Bonjour, l'erreur que vous signalez ne montre pas de lien avec l'extension Advanced Shipping.

Est-ce que vous utilisez des templates personnalisés ?

Est-ce que vous utilisez d'autres modules qui modifient le comportement de la page checkout ?

Cordialement,  
A.L.
