### ISSUE TITLE
$(...).phpConfigEditor is not a function (magento 2.2.6 + dernière version + multilingue)

### ISSUE THREAD

**Issue by jgcabanas** [owebia/magento2-module-advanced-setting-core#11]
Bonjour,
j'ai cette erreur :dans la console : 
$('#carriers_owsh1_config').phpConfigEditor(); 
VM5712:5 Uncaught TypeError: $(...).phpConfigEditor is not a function
Qui empêche toute opération et semble faire bugger mon site.
Avez-vous déjà rencontré une telle erreur ?
Merci pour votre aide

**Comment by owebia** [comment]
Bonjour,
Ce problème peut avoir plusieurs causes.
Quelques solutions sont données ici : https://github.com/owebia/magento2-module-advanced-setting-core/issues/7
Cordialement,
A.L.

**Comment by owebia** [comment]
Duplicate of #7
