### ISSUE TITLE
Error - Source class "\PhpParser\Parser" for "PhpParser\ParserFactory" generation does not exist.

### ISSUE THREAD

**Issue by vikasneoventis** [owebia/magento2-module-advanced-setting-core#2]
How can we add PhpParser\Parser in magento 2 ? I have checked config.json . It requirs "nikic/php-parser". Can you please let em know how we can install this. This is a liberary. Where can we place it.

**Comment by owebia** [comment]
Hello,
You have to use composer to install the dependencies.
Regards,
A.L.

**Comment by vikasneoventis** [comment]
We have used composer. It gives result below.

Using version ^3.0 for nikic/php-parser
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing nikic/php-parser (v3.0.5): Downloading (connecting...)Downloading (0%)           
  Downloading (5%)
  Downloading (10%)
  Downloading (15%)
  Downloading (20%)
  Downloading (25%)
  Downloading (30%)
  Downloading (35%)
  Downloading (40%)
  Downloading (45%)
  Downloading (50%)
  Downloading (55%)
  Downloading (60%)
  Downloading (65%)
  Downloading (70%)
  Downloading (75%)
  Downloading (80%)
  Downloading (85%)
  Downloading (90%)
  Downloading (100%)
Writing lock file
Generating autoload files

After that we did not see files any where in the website. And agin shipping extension gives same error. Please help.

Kind regards,
Vikas

**Comment by owebia** [comment]
In which directory did you execute composer ? In Magento root directory ?

The dependencies must be installed in Magento vendor directory. If you execute composer in Magento root directory, the dependencies will be placed in the good place.

Please refresh cache after.

**Comment by vikasneoventis** [comment]
We placed below code in root composer.json

 "require": {
        "magento/product-community-edition": "2.1.5",
        "composer/composer": "@alpha",
		"nikic/php-parser": "3.0.*"
    },

I have checked it. There is no folder in vendor folder (nicki or PhpParse).

**Comment by vikasneoventis** [comment]
Firstly we paced that code in root composer file and then placed composer.phar file at root and then we run command through shell and it gave result that i have placed in my second message. But extension is giving same error.

**Comment by owebia** [comment]
The dependencies must not be specified in composer, you must install the whole extension using composer :  

composer require owebia/magento2-module-advanced-shipping-setting:^2.0

**Comment by vikasneoventis** [comment]
Can you please explain the steps ? We just need to run this command through shell.

**Comment by vikasneoventis** [comment]
can you please let me know the path of composer ?

**Comment by owebia** [comment]
This is the standard way to use composer:  
https://getcomposer.org/doc/00-intro.md#installation-linux-unix-osx

You can replace `composer` by `php composer.phar` if you use a local installation.

So, go into Magento root directory and execute the command
```
cd /your/magento/root/directory
php composer.phar require owebia/magento2-module-advanced-shipping-setting:^2.0
```

It will install the extension Owebia Advanced Shipping Setting and all dependencies.

Composer uses packagist.org to find the dependencies:

* https://packagist.org/packages/owebia/magento2-module-advanced-shipping-setting
* https://packagist.org/packages/owebia/magento2-module-advanced-setting-core  
* https://packagist.org/packages/nikic/php-parser

**Comment by vikasneoventis** [comment]
Thank you so much for your support. I have done it.
