### ISSUE TITLE
Composer Dependance nikic/php-parser 4

### ISSUE THREAD

**Issue by PierreLeMaguer** [owebia/magento2-module-advanced-setting-core#6]
Hi,
Is it possible to test and replace "nikic/php-parser": "3.1.*" by "nikic/php-parser": "3.1.*|4.*" ? One of my dependances uses only the version 4 of nikic/php-parser. So I can't install your module.
Can you have a look on please ?
Thanks.

**Comment by owebia** [comment]
Hi,

I had a look and it requires some modifications to keep compatibility with both v.3 and v.4 (required as v.4 is not compatible with PHP < 7).

I have made some tests and fixed some issues but it will require a more complete test before it can be released.

Best Regards,
A.L.

**Comment by owebia** [comment]
See commit c0bf6b1a9431c061a604c5ec19d630ee87824350

**Comment by owebia** [comment]
Use magento2-module-advanced-setting-core:^2.3.0 to get this compatibility
