### ISSUE TITLE
$(...).phpConfigEditor is not a function

### ISSUE THREAD

**Issue by hanego** [owebia/magento2-module-advanced-setting-core#7]
I upgraded recently my Magento to 2.3.2 (probably unrelated) and the owebia setting core module might also have been upgraded.
Now I have this error on the config screen in the console:
$(...).phpConfigEditor is not a function
It seems this file is never imported in the head. Did I miss a setting to do?

**Comment by owebia** [comment]
Hi,

Please follow every step of installation like explained here:  
https://github.com/owebia/magento2-module-advanced-shipping/issues/66#issuecomment-534879256

Best Regards,
A.L.

**Comment by hanego** [comment]
Hi, 
I followed the steps without success. After deeply looking at the error in console, I add another error with RequireJs and another library, that was preventing phpConfigEditor to load.
Sorry for the trouble.

**Comment by owebia** [comment]
Hi @hanego , thanks for your feedback.  
Can you give us the name of the other library if any other user encounter the same error message?

**Comment by hanego** [comment]
Hi @owebia, I had in my theme (view/adminhtml/layout/admin_html_system_config.xml) the following:
        <css src="jquery/colorpicker/css/colorpicker.css"/>
        <link src="jquery/colorpicker/js/colorpicker.js"/>
I just commented out those lines. I think it was causing an issue with a similar library in your module.

**Comment by owebia** [comment]
@hanego sorry, I don't see the lines in your comment

**Comment by thebeanieman** [comment]
Hello,

I am having the same problem with Magento ver. 2.2.9. 

`Uncaught TypeError: $(...).phpConfigEditor is not a function
    at (index):487
    at Object.execCb (58b2ca03037b85a43e9f0c572982b532.js:1650)
    at Module.check (58b2ca03037b85a43e9f0c572982b532.js:866)
    at Module.<anonymous> (58b2ca03037b85a43e9f0c572982b532.js:1113)
    at 58b2ca03037b85a43e9f0c572982b532.js:132
    at 58b2ca03037b85a43e9f0c572982b532.js:1156
    at each (58b2ca03037b85a43e9f0c572982b532.js:57)
    at Module.emit (58b2ca03037b85a43e9f0c572982b532.js:1155)
    at Module.check (58b2ca03037b85a43e9f0c572982b532.js:917)
    at Module.enable (58b2ca03037b85a43e9f0c572982b532.js:1143)`

I have disabled every single module except the Magento ones with:
php bin/magento module:disable --clear-static-content

Then when the only modules enabled are the Magento ones and:
Owebia_AdvancedSettingCore
Owebia_AdvancedShippingSetting

I get the error and it breaks the admin layout. Can you please let me know how to fix this or how I can debug this please?

Thanks,
David

**Comment by thebeanieman** [comment]
I can see this javascript file is not loading for some reason:
magento2-module-advanced-setting-core/view/adminhtml/web/js/php-config-editor.js

Thanks,
David

**Comment by owebia** [comment]
Hi,

Did you follow every step of installation?

https://github.com/owebia/magento2-module-advanced-shipping#installation

In your case, remove old package, install new one and deploy static content are important steps.

Best Regards,

A.L.

**Comment by hanego** [comment]
> @hanego sorry, I don't see the lines in your comment

sorry, i missed the nofitications.
I removed the following lines from the adminhtml_system_config_edit.xml:
```
        <css src="jquery/colorpicker/css/colorpicker.css"/>
        <link src="jquery/colorpicker/js/colorpicker.js"/>
```
It is now:
```
<?xml version="1.0" encoding="UTF-8"?>
<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" layout="admin-2columns-left" xsi:noNamespaceSchemaLocation="../../../../../../../lib/internal/Magento/Framework/View/Layout/etc/page_configuration.xsd">
    <head>
<!--        <css src="jquery/colorpicker/css/colorpicker.css"/>-->
<!--        <link src="jquery/colorpicker/js/colorpicker.js"/>-->
    </head>
</page>
```
I suspect there was a conflict with another module.

**Comment by thebeanieman** [comment]
Hello both,

Thank you, you helped me fix this.

I edited this file /app/code/Etheme/Myshop/view/adminhtml/layout/adminhtml_system_config_edit.xml to be:

`<?xml version="1.0" encoding="UTF-8"?>
<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" layout="admin-2columns-left" xsi:noNamespaceSchemaLocation="../../../../../../../lib/internal/Magento/Framework/View/Layout/etc/page_configuration.xsd">
    <head>
    	
        <css src="Owebia_AdvancedSettingCore::css/php-config-editor.css"/>
        <script src="Owebia_AdvancedSettingCore::js/php-config-editor.js"/>
    </head>
</page>`

Refreshed my layout cache and now it works perfectly! I think this file is overriding the adminhtml_system_config_edit.xml  in your module and not loading the javascript.

Thanks,
David

**Comment by owebia** [comment]
Hi,

I think that when `jquery/colorpicker/js/colorpicker.js` is minified and merged, it throws an error preventing the remaining javascript code to be executed.

Thanks to your feedback giving the name of the incriminated theme.

Best Regards,
A.L.

**Comment by thebeanieman** [comment]
No problem. I hope this helps others.

Thanks,
David

**Comment by jmonrove** [comment]
Magecom/Cookiecompliance had the same issue, had to comment out colorpicker
![image](https://user-images.githubusercontent.com/32687858/74881853-ef7a8900-5322-11ea-9140-945cbed16902.png)
