### ISSUE TITLE
composer.json does not allow PHP 7.3

### ISSUE THREAD

**Issue by Yonn-Trimoreau** [owebia/magento2-module-advanced-setting-core#8]
Magento 2.3.3 was just released and brings support for PHP 7.3.
Your composer.json should also allow PHP 7.3 to fully support Magento 2.3.3

**Comment by Yonn-Trimoreau** [comment]
https://github.com/owebia/magento2-module-advanced-setting-core/pull/9

**Comment by owebia** [comment]
Thanks for your PR, fixed in last release
